language: node_js
node_js:
  - stable
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_9e29e8b20af0_key -iv $encrypted_9e29e8b20af0_iv -in .travis/travis_key.enc -out ~/.ssh/travis_key -d
- export TZ='Asia/Shanghai'
- npm install -g hexo
- chmod 600 ~/.ssh/travis_key
- eval $(ssh-agent -s)
- ssh-add ~/.ssh/travis_key
- cp .travis/ssh_config  ~/.ssh/config
- ssh-agent -k
- git config --global user.name "pyclear"
- git config --global user.email cappyclear@gmail.com
install:
- npm install
script:
- hexo clean && hexo g
- travis_wait hexo d
