language: node_js
node_js:
- '7'
branches:
  only:
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_e12a9a075ea1_key -iv $encrypted_e12a9a075ea1_iv
  -in .travis/travis.enc -out ~/.ssh/id_rsa -d
- export TZ='Asia/Shanghai'
- npm install -g hexo
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config  ~/.ssh/config
- git config --global user.name "pyclear"
- git config --global user.email cappyclear@gmail.com
install:
- npm install
script:
- hexo clean && hexo g
- hexo d
