# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: false

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  Categories: /categories
  About: /about
  Flinks: /flinks
# site search option
search: false

# Fancybox
fancybox: true


# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Cobalt Blue

# ===========================================
# Social links Settings
# ===========================================
social:
  email: 
  stack-overflow:
  twitter:
  facebook:
  github: https://github.com/weeklyalgo4groups
  weibo: 
  zhihu: 


# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics: 
# Google Analytics
google_analytics: 

# Duoshuo
duoshuo_shortname: weeklyalgo 
# Disqus
disqus_shortname: 


# ===========================================
# Version
# ===========================================
version: 2.1.0
