nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/pyclear

projects_url: http://github.com/pyclear

customize:
    gravatar:
        email:
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/pyclear
    show_all_posts: false
    post_count: 10
    highlight: solarized-dark

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-91611718-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
